---

- hosts: localhost
  gather_facts: false
  tasks:
    - command: chdir={{inventory_path|dirname}} tower-manage inventory_import --inventory-id={{inventory_id}} --source {{inventory_path|basename}} --overwrite

